language: node_js
node_js:
  - "10"
  - "8"
  - "6"
script: "npm test"
jobs:
  include:
    # v11
    - stage: test Joi v11
      script: |
        npm i -D joi@11
        npm t
    # v12
    - stage: test Joi v12
      script: |
        npm i -D joi@12
        npm t
    # v13
    - stage: test Joi v13
      script: |
        npm i -D joi@13
        npm t
    # v14
    - stage: test Joi v14
      script: |
        npm i -D joi@14
        npm t
